=== carlgauss/ADISysServer/ADISysServer2/bin/business/applicationservice/factory/xml/DTDApplicationServiceMap.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT applicationServiceMap (element*)>

<!ELEMENT element (serviceName,class,method)>

<!ELEMENT serviceName (#PCDATA)> 
<!ELEMENT class (#PCDATA)> 
<!ELEMENT method (#PCDATA)>

=== carlgauss/ADISysServer/bin/business/applicationservice/factory/xml/XMLApplicationServiceMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE applicationServiceMap SYSTEM "DTDApplicationServiceMap.dtd">
<applicationServiceMap>
	<element>
		<serviceName>InserisciPaziente</serviceName>
		<class>ApplicationServicePaziente</class>
		<method>create</method>
	</element>
	<element>
		<serviceName>ModificaPaziente</serviceName>
		<class>ApplicationServicePaziente</class>
		<method>update</method>
	</element>
</applicationServiceMap>

=== carlgauss/ADISysServer/sorgenti/business/applicationservice/factory/xml/XMLApplicationServiceMap.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE applicationServiceMap SYSTEM "DTDApplicationServiceMap.dtd">
<applicationServiceMap>
    <element>
        <serviceName>VisualizzaTuttiPazienti</serviceName>
        <class>ApplicationServicePaziente</class>
        <method>getAll</method>
    </element>
	<element>
		<serviceName>InserisciPaziente</serviceName>
		<class>ApplicationServicePaziente</class>
		<method>create</method>
	</element>
	<element>
		<serviceName>ModificaPaziente</serviceName>
		<class>ApplicationServicePaziente</class>
		<method>update</method>
	</element>
    <element>
        <serviceName>VisualizzaTuttiInfermieri</serviceName>
        <class>ApplicationServiceInfermiere</class>
        <method>getAll</method>
    </element>
    <element>
        <serviceName>VisualizzaTuttiInterventi</serviceName>
        <class>ApplicationServiceIntervento</class>
        <method>getAll</method>
    </element>
</applicationServiceMap>
